# Dependency resolution

ifneq ($(filter $(modules),err),)
modules := eggs schedule $(modules)
endif

ifneq ($(filter $(modules),fields),)
modules := dsl directive-proxy transformations validators $(modules)
endif

ifneq ($(filter $(modules),schedule),)
modules := now-playing timeline show-viewer $(modules)
endif

ifneq ($(filter $(modules),show-viewer),)
modules := language $(modules)
endif

ifneq ($(filter $(modules),timeline),)
modules := language date-picker $(modules)
endif

