#!/bin/bash

cd "$(dirname "$0")"

declare DEMO="${1%.*}"

set -euo pipefail

if [ -z "$DEMO" ]; then
	echo "No demo specified"
	exit 1
fi

declare SOURCE="$DEMO.md"
declare TARGET="./doc-demos/$DEMO/"

if ! [ -f "$SOURCE" ]; then
	echo "Demo not found: $DEMO"
	exit 2
fi

mkdir -p "$TARGET"

echo "Extracting sources from documentation"
./md2demo "$TARGET" < "$SOURCE" | sed -E 's/^/ + /g'
echo ""

# Workaround 
declare -a DEPS=( '' )

if [ -f "../$DEMO/module.js" ]; then
	DEPS+=( "$DEMO" )
fi

DEPS+=( $(perl -ne 'while (<>) { next unless /^Dependencies:\s+(.*)$/; s/^Dependencies:\s+//g; s/[,\s]\s*/\n/g; chomp; print "$_"; }' < "$SOURCE" | sort | uniq) )

echo "Importing dependencies"
declare DEP
for DEP in "${DEPS[@]}"; do
	if [ -z "$DEP" ]; then
		continue
	fi
	echo -n " + $DEP... "
	if ! [ -f "../$DEP/module.js" ]; then
		echo "Dependency not found!"
		exit 3
	fi
	echo ""
	cp -Rvt "$TARGET" "../$DEP" | sed -E 's/^/   - /g'
	echo ""
done

echo "Done!"
